import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import '@/app/styles/globals.css'
import { HttpProvider } from './services/http'

export type TRootLayout = Readonly<{
  children: React.ReactNode
}>

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: TRootLayout) => {
  return (
    <html lang='es-PE'>
      <body
        className={`${roboto.variable} font-roboto antialiased`}
        suppressHydrationWarning={true}
      >
        <HttpProvider>{children}</HttpProvider>
      </body>
    </html>
  )
}

export default RootLayout
